### ISSUE TITLE
Bump inquire to v0.5.2

### ISSUE THREAD

**Issue by mikaelmello** [lunjon/todo#15]
Hey so I just created an issue on another repo of yours :)

https://github.com/lunjon/dotfiles/issues/22

I believe the same applies here, have a good day!

**Comment by lunjon** [comment]
> Hey so I just created an issue on another repo of yours :)
> 
> [lunjon/dotfiles#22](https://github.com/lunjon/dotfiles/issues/22)
> 
> I believe the same applies here, have a good day!

That's correct, @mikaelmello! And thank you for the awesome crate!
